[features]
seeds = false
[programs.devnet]
myepicproject = "5GL5W926zMTvvFtgwX2wuM4ckjxVhXYnioTcsA5XNTzd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/elke/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 

